# Full Resilmesh Platform
include:
  - ./Aggregation/docker-compose-Full_Platform.yml
  - ./Security-Operations/docker-compose-Full_Platform.yml
  - ./Situation-Assessment/docker-compose-Full_Platform.yml
  - ./Threat-Awareness/docker-compose-Full_Platform.yml

services:
  resilmesh_redis:
    hostname: "redis"
    container_name: resilmesh_redis
    restart: unless-stopped
    image: valkey/valkey:7.2
    expose:
      - 6379
    networks:
      resilmesh_network:

networks:
  resilmesh_network:
    external: true
    name: resilmesh_network