temporal:
  url: "resilmesh_sap_wo_temporal:7233"
  namespace: default
  easm_task_queue: easm
  nmap_task_queue: nmap
  cve_connector_task_queue: cve_connector
  slp_enrichment_task_queue: slp_enrichment

neo4j:
  password: supertestovaciheslo
  bolt: bolt://resilmesh_sap_neo4j:7687
  user: neo4j

redis:
  host: resilmesh_sap_casm_redis
  port: 6379

isim:
  url: "http://isim:8000"

nmap_basic:
  targets:
    - resilmesh_sap_casm_metasploitable3
  arguments: "-sV -A"

nmap_topology:
  targets:
    - resilmesh_sap_casm_metasploitable3
  arguments: "-sn -n --traceroute"

easm_scanner:
  domains:
    - vulnweb.com
  mode: fast  # fast or complete
  httpx_path: "/app/go/bin/httpx"
  threads: 100   # required only for complete mode
  wordlist_path: "/app/temporal/easm/subdomainwordlist.txt"  # required only for complete mode

slp_enrichment:
  x_api_key: ""

cve_connector:
  nvd_api_key: ""